security:
    encoders:
        App\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 10
        
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\FormulaireLoginAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/accueil, roles: ROLE_USER }
        - { path: ^/login, allow_if: "!is_authenticated()" }